[package]
name = "pps-time"
description = "A Rust interface for PPS devices"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/pendulum-project/pps-time"
homepage = "https://github.com/pendulum-project/pps-time"

[dependencies]
libc = "0.2.168"
